services:
  app:
    build:
        context: .
        dockerfile: dev.dockerfile
    command: "cargo watch -x run"
    volumes:
        - ./src:/app/src
    ports:
        - "3030:3030"
    env_file:
        - .env